# Generated by Django 5.2.4 on 2025-07-17 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('registration_end', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(default='Will be Disclosed', max_length=300)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('banner_image', models.ImageField(upload_to='event_banners/')),
                ('key_points', models.TextField(help_text='Enter event highlights / bullet points')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('std_id', models.CharField(max_length=50)),
                ('is_hostler', models.BooleanField()),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
