# Generated by Django 5.2.4 on 2025-07-21 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='std_name',
            new_name='Student_name',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='std_id',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='collage_name',
            field=models.CharField(default='Guru Nanak Dev University', max_length=500),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.event'),
        ),
    ]
