# Generated by Django 5.2.4 on 2025-07-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_std_name_eventregistration_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='whatsapp_group',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
